baseURL = "https://thiac.github.io/"
theme = "hugo-goa"
author = "thiac"
title = "Another Hugo "
builddrafts = false
canonifyurls = false
languageCode = "en-US"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"


[params]
author = "thiac"
intro = "The heart is a child"
description = "Description"
authorimage = "mg.jpg"
dateformat = "Jan 2, 2018"

[params.meta]
description = "Simple minimalist theme"
keywords = "minimalist,blog,goa,hugo,developer"

[params.social]
github = "<username>"
twitter = "<username>"
facebook = "<username>"
google = "<username>"
stackoverflow = "<username>"
email = "you@example.com"

[params.extra]
copyright = "copyright @ Rajesh Shenoy"
poweredby = true
highlightjs = true

[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/post/"


[[menu.main]]
    name = "about"
    weight = 100
    identifier = "about"
    url = "/post/"
